### ISSUE TITLE
Support of DES instead of just CSA

### ISSUE THREAD

**Issue by bsg75** [manio/vdr-plugin-dvbapi#101]
I have heard that some Power*U provides use DES for encryption instead of CSA.
Are there any plans to support DES in vdr-plugin-dvbapi?

**Comment by manio** [comment]
AFAICT encryption is forced by DVB standard - and it is the CSA. Please provide more technical details.

**Comment by Yuri666** [comment]
https://github.com/gfto/oscam/commit/be07d0245d13f0d638f24fcf2d55a791c614597c

**Comment by newspaperman** [comment]
Does it matter, what the DVB standard says, if their are DVB compliant muxes out there that actually don't use CSA but DES?

**Comment by manio** [comment]
@newspaperman
It doesn't matter and has to be supported. I didn't tell that it will be not supported because it is not a DVB standard. In fact it has to be some kind of standard if it is currently broadcasted by some providers/channels. ATM I don't have a possibilities and time to write this implementation.

Can somebody confirm that this DES encryption is now supported in any Linux DVB software, like tvheadend, mumudvb?
I am not asking about OpenEnigma, which is supported for some time in the OSCam and it's depending on hardware/driver and OE version.

**Comment by bsg75** [comment]
tvheadend seems to have AES and DES support. See:
https://github.com/tvheadend/tvheadend/blob/master/src/descrambler/tvhcsa.c
and
https://github.com/tvheadend/tvheadend/blob/master/src/descrambler.h

**Comment by manio** [comment]
@bsg75
I am aware of this code, but is somebody using it? Is it working with the OSCam AES/DES support? I think it is only for a SAT/IP devices, which are connected with tvheadend.

**Comment by Yuri666** [comment]
In tvheadend powervu channels works with oscam only in stream mode.
Support for extended CW API at tvheadend in todo list: https://tvheadend.org/issues/3360
