### ISSUE TITLE
Buffer overflow

### ISSUE THREAD

**Issue by AndreyPavlenko** [manio/vdr-plugin-dvbapi#112]
Hi,

There is a similar issue filed against VNSI - https://github.com/FernetMenta/vdr-plugin-vnsiserver/issues/55, however I can reproduce it with streamdev as well. Thus, I assume the issues is in DVBAPI and it was introduced by this commit - 837043e3d768ae46bf1cb39020b8c8865b6036f6. If I roll back this commit both vnsi and streamdev work fine.

Here is the log with streamdev - http://pastebin.com/UUCvh5SV .

**Comment by manio** [comment]
Can you provide similar logs for the case when it is working ok after the same channel starts? I cannot reproduce this problem here. The buffer overflow is probably because your VDR want to stop decrypt the channel.

Can you also try my fastecm branch? Is it better when you use it?

And I don't understand how this is related with FernetMenta/vdr-plugin-vnsiserver#55? Please explain.

**Comment by AndreyPavlenko** [comment]
I think that both errors are caused by the same issue which results to buffer overflow. If I revert the commit mentioned above both errors disappear.

I'll provide you the logs a bit later today.

**Comment by AndreyPavlenko** [comment]
Here is the log reproduced with c97e154 - http://pastebin.com/ZKpfeXkU .
Tried with the fastecm branch - the same issue - buffer overflow.

**Comment by FernetMenta** [comment]
the commit in question is also the cause for https://github.com/FernetMenta/vdr-plugin-vnsiserver/issues/57#issuecomment-229324513

The channel starts to stream and out of a sudden the stream is scrambled again. A revert of this commit cures the issue.

**Comment by manio** [comment]
Ok, it seems that it has to be done properly, for now I am reverting this commit.
Thanks guys!
