### ISSUE TITLE
VDR dies, if all DVB Devices are busy

### ISSUE THREAD

**Issue by 3PO** [manio/vdr-plugin-dvbapi#83]
Hi,

in case, if all DVB Devices are busy (-> live-TV and recording) and i zapping some enciphered channels up and/or down, the VDR dies with a kernel trap: :(

> Dec 24 19:06:53 [kernel] traps: receiver on dev[22415] general protection ip:7fc8a51c46ee sp:7fc79f5f55c8 error:0 in libvdr-dvbapi.so.2.1.6[7fc8a51a5000+28000]

it doesn't matter, if i use FFDESCA, or LIBCSA, the result is the same.
I'am using dvbapi in "Network Mode".

Backtrace: --> https://bpaste.net/show/a7d22cfa2ecd

**Comment by manio** [comment]
Guys, if you have some time, please test if the following patch fixes the problem:
http://skyboo.net/pub/issue83-v1.diff
Apply it on a current git master version.

**Comment by 3PO** [comment]
Hi,

since vdr-2.1.7, it seems the Problem, described above, does not longer exist, so the patch isn't necessary.

**Comment by manio** [comment]
Ok, so closing the issue. Thank you for the input.

**Comment by johnydo** [comment]
Same here. Thank you!

 

 

Von: 3PO [mailto:notifications@github.com] 
Gesendet: Samstag, 7. Februar 2015 11:31
An: manio/vdr-plugin-dvbapi
Cc: johnydo
Betreff: Re: [vdr-plugin-dvbapi] VDR dies, if all DVB Devices are busy (#83)

 

Hi,

since vdr-2.1.7, it seems the Problem, described above, does not longer exist, so the patch isn't necessary.
