### ISSUE TITLE
Enhancement: TS Buffering

### ISSUE THREAD

**Issue by Quantomax** [manio/vdr-plugin-dvbapi#98]
Would it be possible, to buffer, let's say a up to second, of TS Data in Memory, so that the just calculated ecm is needed that second later?

AKA: ECM -> Send to CAM -> Buffer -> Get  CW -> Descramble "with minimal timeshift"

Regards,
Q.

**Comment by manio** [comment]
Hi. It would be maybe possible before, but now now as the plugin is decrypting and pushing data back to vdr as soon as possible. There is no buffering in the plugin, in VDR only. Even if it was possible I am trying to zap with minimal delay, not adding extra lag. Also please note that the stream must be keep in sync with the ECMs - otherwise it will make distortions when the key get sooner or later to the decrypter.

You can search for offline decryption tools if you wish.
